AllCops:
  TargetRubyVersion: 3.0.2
  Exclide:
    - 'tmp/**/*'
Lint/UselessMethodDefinition:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
